Repository inf112-v21/Runtime-Terror-Import-Team_Name-Error-404-Team-Name-Not-Found, pull requests merged in 2021-02, with the labels that each got.

#8 Update README.md
  README.md
Labels: documentation

#7 Mvp one
  README.md
  assets/RoboRally.tsx
  assets/Robot.png
  assets/map_001.tmx
  assets/player.png
  pom.xml
  src/main/java/inf112/skeleton/app/InputHandler.java
  src/main/java/inf112/skeleton/app/Main.java
  src/main/java/inf112/skeleton/app/RoboRally.java
  src/main/java/inf112/skeleton/app/board/Board.java
  src/main/java/inf112/skeleton/app/board/Direction.java
  src/main/java/inf112/skeleton/app/board/IntVector.java
  src/main/java/inf112/skeleton/app/board/Location.java
  src/main/java/inf112/skeleton/app/grid/Board.java
  src/main/java/inf112/skeleton/app/grid/Grid.java
  src/main/java/inf112/skeleton/app/grid/IBoard.java
  src/main/java/inf112/skeleton/app/grid/IGrid.java
  src/main/java/inf112/skeleton/app/grid/ILocation.java
  src/main/java/inf112/skeleton/app/grid/Location.java
  src/main/java/inf112/skeleton/app/inputHandlers/GameScreenInputHandler.java
  src/main/java/inf112/skeleton/app/inputHandlers/TitleScreenInputHandler.java
  src/main/java/inf112/skeleton/app/object/Flag.java
  src/main/java/inf112/skeleton/app/object/Hole.java
  src/main/java/inf112/skeleton/app/object/Player.java
  src/main/java/inf112/skeleton/app/object/Robot.java
  src/main/java/inf112/skeleton/app/screen/GameScreen.java
  src/main/java/inf112/skeleton/app/screen/ParentScreen.java
  src/main/java/inf112/skeleton/app/screen/TitleScreen.java
  src/test/java/inf112/skeleton/app/AppTest.java
  src/test/java/inf112/skeleton/app/board/BoardTest.java
  src/test/java/inf112/skeleton/app/object/RobotTest.java
Labels: Epic, enhancement

#2 Den skriftlige delen av oblig 1
  Deliverables/ObligatoriskOppgave1.md
Labels: documentation, help wanted

#23 Implemented the customizable skin
  assets/skin/uiskin.atlas
  assets/skin/uiskin.json
  assets/skin/uiskin.png
  src/main/java/inf112/skeleton/app/RoboRally.java
  src/main/java/inf112/skeleton/app/screen/TitleScreen.java
  src/test/java/inf112/skeleton/app/AppTest.java
Labels: enhancement

#24 Refactor of the code from assignment 1
  assets/player.png
  src/main/java/inf112/skeleton/app/object/Robot.java
  src/main/java/inf112/skeleton/app/screen/GameScreen.java
  src/main/java/inf112/skeleton/app/screen/TitleScreen.java
  src/test/java/inf112/skeleton/app/AppTest.java
  src/test/java/inf112/skeleton/app/board/BoardTest.java
  src/test/java/inf112/skeleton/app/object/RobotTest.java
Labels: refactor
