Repository inf112-v21/Runtime-Terror-Import-Team_Name-Error-404-Team-Name-Not-Found, pull requests merged in 2021-03, with the labels that each got.

#28 Implemented cards fucntions
  src/main/java/inf112/skeleton/app/Main.java
  src/main/java/inf112/skeleton/app/object/Card.java
  src/main/java/inf112/skeleton/app/object/CardType.java
  src/main/java/inf112/skeleton/app/object/Deck.java
  src/main/java/inf112/skeleton/app/object/GameElements.java
  src/main/java/inf112/skeleton/app/object/Player.java
Labels: enhancement

#31 Oblig2 document
  Deliverables/Diagram/classdiagram.png
  Deliverables/ObligatoriskOppgave2.md
  README.md
Labels: documentation

#36 Added a status badge for build
  README.md
Labels: documentation

#38 New UI
  assets/skin/DotGothic16-Regular(6).fnt
  assets/skin/ShareTechMono-Regular(2).fnt
  assets/skin/arial_black.fnt
  assets/skin/arial_black.png
  assets/skin/uiskin.atlas
  assets/skin/uiskin.json
  assets/skin/uiskin.png
  src/main/java/inf112/skeleton/app/RoboRally.java
  src/main/java/inf112/skeleton/app/inputHandlers/GameScreenInputHandler.java
  src/main/java/inf112/skeleton/app/inputHandlers/TitleScreenInputHandler.java
  src/main/java/inf112/skeleton/app/screen/GameScreen.java
  src/main/java/inf112/skeleton/app/screen/ParentScreen.java
  src/main/java/inf112/skeleton/app/screen/TitleScreen.java
Labels: enhancement

#40 Tests
  src/main/java/inf112/skeleton/app/inputHandlers/GameScreenInputHandler.java
  src/test/java/inf112/skeleton/app/object/BeltTest.java
  src/test/java/inf112/skeleton/app/object/CardTest.java
  src/test/java/inf112/skeleton/app/object/DeckTest.java
  src/test/java/inf112/skeleton/app/object/ExpressBeltTest.java
  src/test/java/inf112/skeleton/app/object/RobotTest.java
  src/test/java/inf112/skeleton/app/object/WallTest.java
Labels: refactor

#39 Added the deliverable text for assignment 3
  Deliverables/Diagram/classdiagram2.png
  Deliverables/Diagram/projectboard.png
  Deliverables/ObligatoriskOppgave3.md
Labels: documentation
